### ISSUE TITLE
Not An Issue

### ISSUE THREAD

**Issue by ismailyilmaz** [elbandit/PPPDDD#11]
@elbandit I bought your design patterns book from amazon and i learned  a lot from it as specially from case study parts, i honestly can say that i learned everything that about desing patters from you, really a big thanks! I was thinking over buyin your this book too but before buying I would like to check it out to make desicion but i couldnt see casestudy(very important!!) and cqrs(i do want to learn it from you!!) projects on here, is there anything im missing or you have a privacy plan?

**Comment by NetChris** [comment]
@ismailyilmaz, look to [the eBidder solution](https://github.com/elbandit/PPPDDD/tree/master/19%20-%20Aggregates/PPPDDDChap19.eBidder).  It contains the primary "case study" for the book.

**Comment by ismailyilmaz** [comment]
@NetChris its nearly an empty solution, just few classes and few lines of codes inside of it. @elbandit 's other book's(Asp.Net Design Patterns) case study project was much, much more larger than this. I think he should answer me as soon as possible here on github or i will tweet him on twitter:)
